export const loadCustomerLogin = "LOAD_CUSTOMER_LOGIN";

export const updateUser = "UPDATE_USER";

export const logoutAuthorize = "LOGOUT_AUTHORIZE";

export const isLandingSearchAvailable = "IS_LANDING_SEARCH_AVAILABLE";

export const landingSearchOnBudget = "LANDING_SEARCH_ON_BUDGET";

// export const = ''

export const LOAD_HOST_LOGIN = "LOAD_HOST_LOGIN";

export const LOAD_CUSTOMER_SIGNUP = "LOAD_CUSTOMER_SIGNUP";

export const LOAD_LANDING_PAGE_DATA = "LOAD_LANDING_PAGE_DATA";

export const LOAD_CITIES_PAGE_DATA = "LOAD_CITIES_PAGE_DATA";

export const LOAD_HOTELS_PAGE_DATA = "LOAD_HOTELS_PAGE_DATA";

export const LOAD_HOST_LANDING_PAGE_DATA = "LOAD_HOST_LANDING_PAGE_DATA";

export const LOAD_HOST_HOTEL_PAGE_DATA = "LOAD_HOST_HOTEL_PAGE_DATA";

export const SEARCH_ON_FILTER = "SEARCH_ON_FILTER";

export const LOAD_ADMIN_USERS = "LOAD_ADMIN_USERS";

export const LOAD_ADMIN_HOTELS = "LOAD_ADMIN_HOTELS";

export const LOAD_ADMIN_CITIES = "LOAD_ADMIN_CITIES";

export const LOAD_ADMIN_BOOKINGS = "LOAD_ADMIN_BOOKINGS";

export const GET_HOTEL_DETAILS_CUSTOMER = "GET_HOTEL_DETAILS_CUSTOMER";

export const BOOKING_SUMMARY_DATA = "BOOKING_SUMMARY_DATA";

export const LOGIN_USER_REDUCER = "LOGIN_USER_REDUCER";

export const LOGIN_HOST_REDUCER = "LOGIN_HOST_REDUCER";

export const LOAD_CUSTOMER_SIGNUP_REDUCER = "LOAD_CUSTOMER_SIGNUP_REDUCER";

export const UPDATE_USER_REDUCER = "UPDATE_USER_REDUCER";

export const LOGOUT_USER_REDUCER = "LOGOUT_USER_REDUCER";

export const LANDING_SEARCH_BUDGET = "LANDING_SEARCH_BUDGET";

export const SEARCH_ON_FILTER_REDUCER = "SEARCH_ON_FILTER_REDUCER";

export const LOAD_LANDING_PAGE_DATA_REDUCER = "LOAD_LANDING_PAGE_DATA_REDUCER";

export const LOAD_CITIES_PAGE_DATA_REDUCER = "LOAD_CITIES_PAGE_DATA_REDUCER";

export const LOAD_HOTELS_PAGE_DATA_REDUCER = "LOAD_HOTELS_PAGE_DATA_REDUCER";

export const LOAD_HOST_LANDING_PAGE_DATA_REDUCER =
  "LOAD_HOST_LANDING_PAGE_DATA_REDUCER";

export const LOAD_HOST_HOTEL_PAGE_DATA_REDUCER =
  "LOAD_HOST_HOTEL_PAGE_DATA_REDUCER";

export const LOAD_ADMIN_USERS_REDUCER = "LOAD_ADMIN_USERS_REDUCER";

export const LOAD_ADMIN_HOTELS_REDUCER = "LOAD_ADMIN_HOTELS_REDUCER";

export const LOAD_ADMIN_CITIES_REDUCER = "LOAD_ADMIN_CITIES_REDUCER";

export const LOAD_ADMIN_BOOKINGS_REDUCER = "LOAD_ADMIN_BOOKINGS_REDUCER";

export const GET_HOTEL_DETAILS_CUSTOMER_REDUCER =
  "GET_HOTEL_DETAILS_CUSTOMER_REDUCER";

export const BOOKING_SUMMARY_DATA_REDUCER = "BOOKING_SUMMARY_DATA_REDUCER";
